homebrew_packages:
  - openssl
  - coreutils
  - md5sha1sum
  - ctags
  - libxml2
  - libpng
  - freetype
  - ffmpeg
  - readline
  - git
  - ant
  - ack
  - tmux
  - vim
  - zsh
  - rcm
  - reattach-to-user-namespace
  - the_silver_searcher
  - httpie
  - curl
  - vimpager
  - p7zip
  - grep
  - tree
  - heroku
  - hub
  - awscli
  - docker
  - imagemagick
  - qt
  - jmeter
  - libyaml
  - nvm
  - ruby-build
  - rbenv
  - rbenv-default-gems
  - postgresql
  - redis
  - sqlite
  - mongodb
  - mysql
  - chromedriver
  - m-cli
dotfiles:
  - bash_profile
  - vimrc
  - pryrc
  - irbrc
  - gitconfig
  - git_status_in_prompt.sh
gui_applications:
  root:
    - 1password.app
    - Charles.app
    - Mongohub.app
    - Postman.app
    - Slack.app
    - Github Desktop.app
    - XQuartz.app
    - VirtualBox.app
    - Firefox.app
    - Google Chrome.app
    - Atom.app
    - Sublime Text.app
    - Macdown.app
    - Sequel Pro.app
    - MySQLWorkbench.app
  user:
quicklook_plugins:
  root:
  user:
    - QLColorCode
    - QLMarkdown
    - QLPrettyPatch
    - QuickLookCSV
    - QuickLookJSON
empty_directories:
  - ~/Pictures
  - ~/Downloads
  - ~/Documents
  - ~/Desktop
  - ~/Pictures
  - ~/Music
  - ~/Movies
  - ~/Public
  - ~/.Trash
defaults:
  NSGlobalDomain:
    ApplePressAndHoldEnabled: 0
    KeyRepeat: 0
    AppleKeyboardUIMode: 3
    NSAutomaticSpellingCorrectionEnabled: 0
    com.apple.springing.enabled: 1
    com.apple.springing.delay: 0
    WebKitDeveloperExtras: 1
  com.apple.Safari:
    HomePage: about:blank
  com.apple.terminal:
    StringEncodings: 4
  com.apple.screencapture:
    location: ~/Desktop
    type: png
  com.apple.dock:
    tilesize: 36
    mineffect: "scale"
    launchanim: 1
    autohide-delay: 0
  com.apple.Safari:
    com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled: 1
    ProxiesInBookmarksBar: ()
    IncludeInternalDebugMenu: 1
  com.apple.mail:
    AddressesIncludeNameOnPasteboard: 0
